runtime: python37
instance_class: F4_HIGHMEM
entrypoint: gunicorn -b :$PORT main:app
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50
