runtime: python37
#env: flex
#entrypoint: gunicorn -b :$PORT app:app
#
#readiness_check:
#  app_start_timeout_sec: 1800
#
#resources:
# cpu: 2
# memory_gb: 12
# disk_size_gb: 100
resources:
  memory_gb: 4